apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
      - name: backend
        image: pasindu55/aluminium_backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
spec:
  type: NodePort  # Change the service type to NodePort
  selector:
    app: spring-backend
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the Service
      targetPort: 8080  # Port on the backend pods to which traffic should be forwarded
      nodePort: 30000  # Optional: Specify the NodePort value (range: 30000-32767)
