name: CI/CD Docker Compose (No DB)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t my-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t my-frontend:latest ./frontend

      - name: Run Docker Compose (without DB)
        run: docker-compose up -d



      - name: Tear down
        run: docker-compose down
