name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and Push Docker Image
      env:
        REGISTRY: ${{ secrets.AZURE_REGISTRY }}
        USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      run: |
        docker build -t $REGISTRY/your-image-name:latest .
        echo $PASSWORD | docker login $REGISTRY -u $USERNAME --password-stdin
        docker push $REGISTRY/your-image-name:latest

    - name: SSH into Azure VM and Pull Docker Image
      uses: appleboy/ssh-action@v0.4.2
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          docker pull $REGISTRY/your-image-name:latest

    - name: Run Docker Container on Azure VM
      uses: appleboy/ssh-action@v0.4.2
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          docker run -d -p 8080:8080 $REGISTRY/your-image-name:latest
