name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install and run Talisman to detect sensitive data
      run: |
        curl https://thoughtworks.github.io/talisman/install.sh | bash
        mkdir -p ~/talisman
        curl -L https://github.com/thoughtworks/talisman/releases/download/v1.32.0/talisman_linux_amd64 -o ~/talisman/talisman
        chmod +x ~/talisman/talisman
        # Run Talisman scan and continue even if it finds issues
        ~/talisman/talisman --scan || echo "Talisman scan completed with errors, but proceeding with the build."

    - name: Build Docker Image
      run: |
        docker build -t pasindu55/alumini-backend:latest .
        docker tag pasindu55/alumini-backend:latest pasindu55/alumini-backend:${{ github.run_id }}

 

  
