name: CI Docker Compose (No DB, No Push)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t my-backend:latest ./backend

      - name: Build frontend image
        run: docker build -t my-frontend:latest ./frontend

      - name: Run Docker Compose
        run: docker-compose up -d

  
