name: CI Docker Compose (Spring Boot)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v3

      # Step 2: Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Step 3: List files (debugging)
      - name: List repo files
        run: ls -R

      # Step 4: Build backend image
      - name: Build backend image
        run: docker build -t my-backend:latest .

      # Step 5: Optional frontend build
      - name: Build frontend image
        run: |
          if [ -d "./frontend" ]; then
            docker build -t my-frontend:latest ./frontend
          fi

      # Step 6: Copy .env
      - name: Copy .env
        run: cp .env ./docker-compose.env

      # Step 7: Start Docker Compose
      - name: Start Docker Compose
        run: docker compose --env-file docker-compose.env up -d --build

      # Step 8: Wait for backend
      - name: Wait for backend
        run: sleep 20

      # Step 9: Run backend tests
      - name: Run backend tests
        run: |
          CONTAINER_ID=$(docker ps -qf "ancestor=my-backend:latest")
          docker exec $CONTAINER_ID ./run-tests.sh

      # Step 10: Tear down
      - name: Tear down
        run: docker compose down
