name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t pasindu55/alumini-backend:latest .
        docker tag pasindu55/alumini-backend:latest pasindu55/alumini-backend:${{ github.run_id }}

    - name: Login to DockerHub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker Image to Registry
      run: |
        docker push pasindu55/alumini-backend:latest
        

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull pasindu55/alumini-backend:latest &&
          if [ "$(docker ps -q -f name=farmer_app)" ]; then
            docker stop alumini_back
            docker rm alumini_back
          fi &&
          docker run -d --name alumini_back -p 8080:8080 pasindu55/alumini-backend:latest
