name: Deploy Java App with Docker and Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deployname: Deploy Java App with Docker and Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
           docker build -t pasindu55/aluminium_backend .
           docker tag pasindu55/aluminium_backend:latest pasindu55/aluminium_backend:${{ github.sha }}

      # Push Docker Image to Registry (if required)
      - name: Push Docker Image to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push pasindu55/aluminium_backend:${{ github.sha }}

      # Install kubectl
      - name: Install kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      # Debug kubeconfig
      - name: Debug kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}"

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        uses: steebchen/kubectl@master
        with:
           args: set image deployment/my-deployment my-container=pasindu55/aluminium_backend:${{ github.sha }}
        env:
           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

      # Apply Kubernetes deployment
      - name: Apply Kubernetes deployment
        run: |
          kubectl apply -f my-deployment.yaml
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
           docker build -t pasindu55/aluminium_backend .
           docker tag pasindu55/aluminium_backend:latest pasindu55/aluminium_backend:${{ github.sha }}

      # Push Docker Image to Registry (if required)
      - name: Push Docker Image to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push pasindu55/aluminium_backend:${{ github.sha }}

      # Install kubectl
      - name: Install kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      # Debug kubeconfig
      - name: Debug kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}"

      # # Deploy to Kubernetes
      # - name: Deploy to Kubernetes
      #   uses: steebchen/kubectl@master
      #   with:
      #     args: set image deployment/my-deployment my-container=pasindu55/aluminium_backend:${{ github.sha }}
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to Kubernetes
        uses: steebchen/kubectl@master
        with:
           args: set image deployment/my-deployment my-container=pasindu55/aluminium_backend:${{ github.sha }} && kubectl apply -f my-deployment.yaml
        env:
           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

