name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Angular App
        run: npm install && npm run build --prod

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t pasindu55/aluminium_backend .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push pasindu55/aluminium_backend

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Use SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 4.213.119.32 >> ~/.ssh/known_hosts

      - name: Run Docker Container
        run: |
          ssh user@4.213.119.32 'docker run -d -p 8080:8080 pasindu55/aluminium_backend'
