name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        echo ${{ secrets.AZURE_DOCKER_PASSWORD }} | docker login -u ${{ secrets.AZURE_DOCKER_USERNAME }} --password-stdin
        docker build -t my-spring-app .
        docker tag my-spring-app ${{ secrets.AZURE_DOCKER_REGISTRY }}/my-spring-app:latest
        docker push ${{ secrets.AZURE_DOCKER_REGISTRY }}/my-spring-app:latest

    - name: SSH into Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
        script: |
          docker stop my-spring-app || true
          docker rm my-spring-app || true
          docker pull ${{ secrets.AZURE_DOCKER_REGISTRY }}/my-spring-app:latest
          docker run -d -p 8080:8080 --name my-spring-app ${{ secrets.AZURE_DOCKER_REGISTRY }}/my-spring-app:latest
